# Generated by Django 3.0.5 on 2020-05-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20200504_2226'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicprofile',
            name='user_plants',
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.PublicProfile')),
            ],
        ),
    ]
