# Generated by Django 3.0.5 on 2020-05-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200505_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='nickname',
            field=models.CharField(default='', max_length=25),
        ),
    ]
