# Generated by Django 3.0.5 on 2020-05-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200506_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='image',
            field=models.ImageField(blank=True, upload_to='userplant_pic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_pic'),
        ),
    ]
