# Generated by Django 3.0.5 on 2020-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200507_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplant',
            old_name='image',
            new_name='userplant_image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='user_image',
        ),
    ]
