# Generated by Django 3.0.5 on 2020-05-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200515_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followeduser',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='profiles.UserProfile'),
        ),
        migrations.AlterField(
            model_name='followeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
