# Generated by Django 3.0.5 on 2020-07-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200625_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='userplant_image',
            field=models.ImageField(blank=True, upload_to='userplant_images/'),
        ),
    ]
