# Generated by Django 3.0.5 on 2020-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sun_pref',
            field=models.CharField(choices=[(1, 'High'), (2, 'Med/High'), (3, 'Med'), (4, 'Med/Low'), (5, 'Low'), (6, 'Any')], max_length=20),
        ),
    ]
